#ifndef	CONSTS_HPP_
#define CONSTS_HPP_

#define	WEBSERV_MAX_CONNS			4096
#define WEBSERV_REQUEST_BUFFER_SIZE	4096
#define	WEBSERV_CLIENT_TIMEOUT		60
#define WEBSERV_METHODS_SUPPORTED	3

#define WEBSERV_SERVER_VERSION		"Webserv/v1.0"
#define WEBSERV_DEFAULT_ROOT_DIR	"tests/www/html"

#endif  // CONSTS_HPP_
