#ifndef	CONSTS_HPP_
#define CONSTS_HPP_

#define WEBSERV_SERVER_VERSION		"Webserv/v1.0"
#define WEBSERV_DEFAULT_ROOT_DIR	"tests/www/html"

#define	WEBSERV_MAX_CONNS			4096
#define WEBSERV_REQUEST_BUFFER_SIZE	4096
#define	WEBSERV_CLIENT_TIMEOUT		60
#define WEBSERV_METHODS_SUPPORTED	3

#define WEBSERV_CGI_TIMEOUT			1
#define WEBSERV_CGI_TICKS_MS		10

#define WEBSERV_SESSION_ID_LENGTH 	32
#define WEBSERV_SESSION_TIMEOUT		600
#define WEBSERV_SESSION_ID			"WEBSERV_SESSION_ID"
#define WEBSERV_COOKIE_PREFIX		"WEBSERV_"

#endif  // CONSTS_HPP_
