#ifndef CONF_ENUMS_HPP_
#define CONF_ENUMS_HPP_

namespace Webserv {
namespace Conf {

enum	E_CONF_TOKEN {
	CONF_EMPTY_TOKEN = 0,
	CONF_NOT_FOUND_TOKEN,
	CONF_ERRORENOUS_TOKEN,
	CONF_SERVER_NAME,
	CONF_SERVER_LISTEN,
	CONF_SERVER_OPENING,
	CONF_SERVER_LOCATION,
	CONF_BLOCK_CGI,
	CONF_BLOCK_ROOT,
	CONF_BLOCK_INDEX,
	CONF_BLOCK_CLOSING,
	CONF_BLOCK_AUTOINDEX,
	CONF_BLOCK_REDIRECT,
	CONF_BLOCK_ERROR_PAGE,
	CONF_BLOCK_BODY_LIMIT,
	CONF_BLOCK_UPLOAD_PASS,
	CONF_BLOCK_ALLOWED_METHODS,
	CONF_TOKEN_MAX
};

}  // namespace Conf
}  // namespace Webserv

#endif  // CONF_ENUMS_HPP_
